package com.example.gacha_data.local

import com.example.core.util.CookieConstants.AMBUSH
import com.example.core.util.CookieConstants.ANCIENT
import com.example.core.util.CookieConstants.CHARGE
import com.example.core.util.CookieConstants.COMMON
import com.example.core.util.CookieConstants.DEFENSE
import com.example.core.util.CookieConstants.EPIC
import com.example.core.util.CookieConstants.HEALING
import com.example.core.util.CookieConstants.LEGENDARY
import com.example.core.util.CookieConstants.MAGIC
import com.example.core.util.CookieConstants.RANGED
import com.example.core.util.CookieConstants.RARE
import com.example.core.util.CookieConstants.SUPPORT
import com.example.core.data.local.entity.CookieEntity
import com.example.core.R
import com.example.core.util.CookieConstants.BOMBER
import com.example.core.util.CookieConstants.FRONT

object DefaultCookieList {
    val list = listOf(
        CookieEntity(
            name = "Pure Vanilla",
            soulStoneImage = R.drawable.pure_vanilla_soulstone,
            cookieImage = R.drawable.pure_vanilla_character_card,
            cookieImageAnimated = R.drawable.pure_vanilla_animated,
            cookieGachaImage = R.drawable.pure_vanilla_face_icon,
            type = HEALING,
            rarity = ANCIENT,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Angel Cookie",
            soulStoneImage = R.drawable.angel_cookie_soulstone,
            cookieImage = R.drawable.angel_cookie_character_card,
            cookieImageAnimated = R.drawable.angel_cookie_animated,
            cookieGachaImage = R.drawable.angel_cookie_face_icon,
            type = HEALING,
            rarity = LEGENDARY,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Avocado Cookie",
            soulStoneImage = R.drawable.avocado_cookie_soulstone,
            cookieImage = R.drawable.avocado_cookie_character_card,
            cookieImageAnimated = R.drawable.avocado_cookie_animated,
            cookieGachaImage = R.drawable.avocado_cookie_face_icon,
            type = DEFENSE,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Beet Cookie",
            soulStoneImage = R.drawable.beet_cookie_soulstone,
            cookieImage = R.drawable.beet_cookie_character_card,
            cookieImageAnimated = R.drawable.beet_cookie_animated,
            cookieGachaImage = R.drawable.beet_cookie_face_icon,
            type = RANGED,
            rarity = COMMON,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Ginger Brave",
            soulStoneImage = R.drawable.ginger_brave_soulstone,
            cookieImage = R.drawable.ginger_brave_character_card,
            cookieImageAnimated = R.drawable.ginger_brave_animated,
            cookieGachaImage = R.drawable.ginger_brave_face_icon,
            type = CHARGE,
            rarity = COMMON,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Muscle Cookie",
            soulStoneImage = R.drawable.muscle_cookie_soulstone,
            cookieImage = R.drawable.muscle_cookie_character_card,
            cookieImageAnimated = R.drawable.muscle_cookie_animated,
            cookieGachaImage = R.drawable.muscle_cookie_face_icon,
            type = CHARGE,
            rarity = COMMON,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Ninja Cookie",
            soulStoneImage = R.drawable.ninja_cookie_soulstone,
            cookieImage = R.drawable.ninja_cookie_character_card,
            cookieImageAnimated = R.drawable.ninja_cookie_animated,
            cookieGachaImage = R.drawable.ninja_cookie_face_icon,
            type = AMBUSH,
            rarity = COMMON,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Princess Cookie",
            soulStoneImage = R.drawable.princess_cookie_soulstone,
            cookieImage = R.drawable.princess_cookie_character_card,
            cookieImageAnimated = R.drawable.princess_cookie_animated,
            cookieGachaImage = R.drawable.princess_cookie_face_icon,
            type = CHARGE,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Strawberry Cookie",
            soulStoneImage = R.drawable.strawberry_cookie_soulstone,
            cookieImage = R.drawable.strawberry_cookie_character_card,
            cookieImageAnimated = R.drawable.strawberry_cookie_animated,
            cookieGachaImage = R.drawable.strawberry_cookie_face_icon,
            type = DEFENSE,
            rarity = COMMON,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Wizard Cookie",
            soulStoneImage = R.drawable.wizard_cookie_soulstone,
            cookieImage = R.drawable.wizard_cookie_character_card,
            cookieImageAnimated = R.drawable.wizard_cookie_animated,
            cookieGachaImage = R.drawable.wizard_cookie_face_icon,
            type = MAGIC,
            rarity = COMMON,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Knight Cookie",
            soulStoneImage = R.drawable.soulstone_knight,
            cookieImage = R.drawable.cookie_knight_card,
            cookieImageAnimated = R.drawable.knight_cookie,
            cookieGachaImage = R.drawable.knight_face_icon,
            type = DEFENSE,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = R.drawable.knightskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Blackberry Cookie",
            soulStoneImage = R.drawable.soulstone_blackberry,
            cookieImage = R.drawable.blackberry_cookie,
            cookieImageAnimated = R.drawable.blackberrycookiegachaanimation,
            cookieGachaImage = R.drawable.blackberryhead,
            type = MAGIC,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Adventurer Cookie",
            soulStoneImage = R.drawable.soulstone_adventurer,
            cookieImage = R.drawable.adventurercookiegachaanimation,
            cookieImageAnimated = R.drawable.adventurercookiegachaanimation,
            cookieGachaImage = R.drawable.beet_cookie_face_icon,
            type = AMBUSH,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = R.drawable.advskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Pancake Cookie",
            soulStoneImage = R.drawable.soulstone_pancake,
            cookieImage = R.drawable.cookie_pancake_card,
            cookieImageAnimated = R.drawable.pancakecookiegachaanimation,
            cookieGachaImage = R.drawable.pancake_cookie,
            type = AMBUSH,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = R.drawable.pancakeskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Alchemist",
            soulStoneImage = R.drawable.soulstone_alchemist,
            cookieImage = R.drawable.cookie_alchemist_card,
            cookieImageAnimated = R.drawable.alchemist_cookie_alternate,
            cookieGachaImage = R.drawable.alchemisthead,
            type = BOMBER,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = R.drawable.alchskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Cherry Cookie",
            soulStoneImage = R.drawable.soulstone_cherry,
            cookieImage = R.drawable.cookie_cherry_card,
            cookieImageAnimated = R.drawable.cherry_cookie,
            cookieGachaImage = R.drawable.cherryhead,
            type = BOMBER,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = R.drawable.cherryskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Gumball Cookie",
            soulStoneImage = R.drawable.soulstone_gumball,
            cookieImage = R.drawable.cookie_gumball_card,
            cookieImageAnimated = R.drawable.gumball_cookie,
            cookieGachaImage = R.drawable.gumballhead,
            type = BOMBER,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = R.drawable.gumskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Carrot Cookie",
            soulStoneImage = R.drawable.soulstone_carrot,
            cookieImage = R.drawable.cookie_carrot_card,
            cookieImageAnimated = R.drawable.carrot_cookie,
            cookieGachaImage = R.drawable.carrothead,
            type = SUPPORT,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = R.drawable.carrotskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Onion Cookie",
            soulStoneImage = R.drawable.soulstone_onion,
            cookieImage = R.drawable.cookie_onion_card,
            cookieImageAnimated = R.drawable.onion_cookie,
            cookieGachaImage = R.drawable.onion_head,
            type = SUPPORT,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = R.drawable.onionskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Clover Cookie",
            soulStoneImage = R.drawable.soulstone_clover,
            cookieImage = R.drawable.cookie_clover_card,
            cookieImageAnimated = R.drawable.clover_cookie_alternate,
            cookieGachaImage = R.drawable.cloverhead,
            type = SUPPORT,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = R.drawable.cloverskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Custard Cookie III",
            soulStoneImage = R.drawable.soulstone_custard,
            cookieImage = R.drawable.cookie_custard_card,
            cookieImageAnimated = R.drawable.custard_cookie,
            cookieGachaImage = R.drawable.custardhead,
            type = SUPPORT,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = R.drawable.custardskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Dark Choco Cookie",
            soulStoneImage = R.drawable.soulstone_darkchoco,
            cookieImage = R.drawable.cookie_dark_choco_card,
            cookieImageAnimated = R.drawable.dark_choco_cookie,
            cookieGachaImage = R.drawable.darkchocohead,
            type = CHARGE,
            rarity = EPIC,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = R.drawable.custardskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Purple Yam Cookie",
            soulStoneImage = R.drawable.soulstone_purpleyam,
            cookieImage = R.drawable.cookie_purple_yam_card,
            cookieImageAnimated = R.drawable.purple_yam,
            cookieGachaImage = R.drawable.yamhead,
            type = CHARGE,
            rarity = EPIC,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = R.drawable.yamskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Werewolf Cookie",
            soulStoneImage = R.drawable.soulstone_werewolf,
            cookieImage = R.drawable.cookie_werewolf_card,
            cookieImageAnimated = R.drawable.werewolf_cookie,
            cookieGachaImage = R.drawable.werewolfbase,
            type = CHARGE,
            rarity = EPIC,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = R.drawable.wereskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Kumiho Cookie",
            soulStoneImage = R.drawable.soulstone_kumiho,
            cookieImage = R.drawable.cookie_kumiho_card,
            cookieImageAnimated = R.drawable.kumiho_cookie_alternate,
            cookieGachaImage = R.drawable.kumihohead,
            type = CHARGE,
            rarity = EPIC,
            soulStoneCount = 0,
            position = "",
            skillDesc = "",
            gameDescription = "",
            skill = "",
            skillIcon = R.drawable.kumihoskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Red Velvet Cookie",
            soulStoneImage = R.drawable.soulstone_redvelvet,
            cookieImage = R.drawable.cookie_red_velvet_card,
            cookieImageAnimated = R.drawable.red_velvet_cookie,
            cookieGachaImage = R.drawable.redvelvethead,
            type = CHARGE,
            rarity = EPIC,
            soulStoneCount = 0,
            position = FRONT,
            skillDesc = "Face the might of the Cakes! This Cookie grasps the rearmost enemy, brings it in front of the Cookie squad, dealing great damage and stunning them for a short time. Cannot be interrupted.",
            gameDescription = "\"OBEY ME, MY BEASTS!\" Red Velvet Cookie's order, like a thunderbolt, rolls over the battlefield. \"FALL IN!\" And the horde of snarling Cake Monsters obediently assumes a dreadful battle formation. The crimson general personally leads his legion into battle, sowing fear with his clenched cake fist and his black eye gleaming with the dark fire of battle fervor. The battle-hardened warrior will see his mission to its end with precision and relentlessness. \"UNLEASH CHAOS, MY BEASTS!\" he roars as the battle begins. Adding silently: \"But please, come back alive...\"\"",
            skill = "Crimson Hand",
            skillIcon = R.drawable.redvelvetskill,
            quote = "“\tTO BATTLE!\t„",
            cooldown = 0,
            skillStats = "20 second base Cooldown\n" +
                    "Single hit DMG: 835.0% (+10%-10.1% per level)\n" +
                    "CRK-stun.png Stun: 5.0 sec"
        ),
        CookieEntity(
            name = "Raspberry Cookie",
            soulStoneImage = R.drawable.soulstone_raspberry,
            cookieImage = R.drawable.cookie_raspberry_card,
            cookieImageAnimated = R.drawable.rasp_illust,
            cookieGachaImage = R.drawable.raspberryhead,
            type = CHARGE,
            rarity = EPIC,
            soulStoneCount = 0,
            position = FRONT,
            skillDesc = "Quickly dashes at the enemy with the highest ATK and continuously stabs them. The attack briefly reduces the hit target's ATK for a while. While Raspberry Cookie is using her skill, she will be more resistant to interrupting effects.",
            gameDescription = "",
            skill = "Raspberry Reprise",
            skillIcon = R.drawable.raspberryskill,
            quote = "“\tFear the scarlet crest!\t„",
            cooldown = 0,
            skillStats = "14 second base Cooldown\n" +
                    "Single (9) hit DMG: 42.0% (+0.56% DMG per level)\n" +
                    "DMG of final hit: 334.0% (+4.54% DMG per level)\n" +
                    "CRK-atkdown.png ATK Reduction: -40.0% for 3.0 sec"
        ),
        CookieEntity(
            name = "TeaKnight Cookie",
            soulStoneImage = R.drawable.soulstone_teaknight,
            cookieImage = R.drawable.cookie_teaknight_card,
            cookieImageAnimated = R.drawable.teaknightgachaillust,
            cookieGachaImage = R.drawable.kumihohead,
            type = CHARGE,
            rarity = EPIC,
            soulStoneCount = 0,
            position = FRONT,
            skillDesc = "Inflicts damage to the nearest enemy (targets Cookies first) and leads the battle on, providing a buff for his allies. There are several kinds of available buffs; each kind is applied to the Cookie meeting the required conditions. Whenever an allied Cookie is defeated, the Wrath of the Commander effect is triggered. Wrath of the Commander cannot be dispelled and stacks up to four times. At maximum stacks, Tea Knight Cookie will become resistant to interrupting effects.",
            gameDescription = "\"There was a time when dreadful dragons ruled the skies. Their fire ravaged entire kingdoms, and their claws crumbled countless Cookies. An order of knight in shiny silver armor, infused with courage and battle prowess, swore to put an end to this threat. Led by Tea Knight Cookie, the knights courageously opposed the gargantuan monsters through fire and jam an remained in history. But even the most fragrant tea loses its aroma--with time, the glorious tale of the knight became a legend, a mere echo of the past. Tea Knight Cookie, the fearless hero, was forgotten by those he strove to protect. Now sadness and regret shadow his scar-ridden face. Perhaps he wanted to be forgotten...? Yet... when he reminisces the battles he fought side by side with his comrades of old, a spark lights up in his eyes: the flame within him still burns bright!\"",
            skill = "Battlemaster",
            skillIcon = R.drawable.tea_knight_skill,
            quote = "Never forget your oaths, young one.",
            cooldown = 18,
            skillStats = "18 second base Cooldown\n" +
                    "Single hit DMG: 542.4% (+7.38% DMG per level)\n" +
                    "ATK Increase: 6.0% for the two Cookies with the highest ATK for 8.0 sec\n" +
                    "Increase: 12.0% for the two Cookies with the highest CRIT% for 8.0 sec\n" +
                    "For each stack of Wrath of the Commander: ATK 50.0%,ATK SPD 20.0%\n" +
                    "Fourth stack of  Wrath of the Commander: ATK 100.0%, ATK SPD 150.0%"
        ),
        CookieEntity(
            name = "Madeleine Cookie",
            soulStoneImage = R.drawable.soulstone_madeleine,
            cookieImage = R.drawable.cookie_madeleine_card,
            cookieImageAnimated = R.drawable.madeleine_cookie,
            cookieGachaImage = R.drawable.soulstone_madeleine,
            type = DEFENSE,
            rarity = EPIC,
            soulStoneCount = 0,
            position = FRONT,
            skillDesc = "Calls upon the Celestial Light that allows performing ranged area attacks instead of regular attacks, While under the Celestial Light, Madeleine Cookie receives a buff making him immune to debuffs.",
            gameDescription = "An offspring of a noble Cookie family from a peaceful republic across the ocean, Madeleine Cookie, armed with his family's influence and shiny new armor, is already the Commander of a knight order. On the day of his Commander's Oathtaking, Madeleine Cookie dedicated himself to the Divine and was granted the Sword and Shield of Radiant Light, which he prizes the most among his numerous possessions. The glorious Knight Commander's usual duties included trotting around the city on his snow-white sugar horse or letting his heavy cape flutter dramatically on the wind during his sparring sessions. Not too long ago, the heroic Madeleine Cookie set on a quest in search of the legendary Jam of Souls capable of granting Cookies eternal life! Will the noble paladin's first campaign bear fruit?",
            skill = "Commander's Honor",
            skillIcon = R.drawable.madeskill,
            quote = "The Divine smiles upon me!",
            cooldown = 18,
            skillStats = "13 second base Cooldown\n" +
                    "Immunity for 10.0 seconds\n" +
                    "Damage dealt: 108.00% (+1.45% DMG per level)"
        ),
    )
}