package com.example.gacha_data.local

import com.example.core.util.CookieConstants.AMBUSH
import com.example.core.util.CookieConstants.ANCIENT
import com.example.core.util.CookieConstants.CHARGE
import com.example.core.util.CookieConstants.COMMON
import com.example.core.util.CookieConstants.DEFENSE
import com.example.core.util.CookieConstants.EPIC
import com.example.core.util.CookieConstants.HEALING
import com.example.core.util.CookieConstants.LEGENDARY
import com.example.core.util.CookieConstants.MAGIC
import com.example.core.util.CookieConstants.RANGED
import com.example.core.util.CookieConstants.RARE
import com.example.core.util.CookieConstants.SUPPORT
import com.example.core.data.local.entity.CookieEntity
import com.example.core.R
import com.example.core.util.CookieConstants.BOMBER

object DefaultCookieList {
    val list = listOf(
        CookieEntity(
            name = "Pure Vanilla",
            soulStoneImage = R.drawable.pure_vanilla_soulstone,
            cookieImage = R.drawable.pure_vanilla_character_card,
            cookieImageAnimated = R.drawable.pure_vanilla_animated,
            cookieGachaImage = R.drawable.pure_vanilla_face_icon,
            type = HEALING,
            rarity = ANCIENT,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Angel Cookie",
            soulStoneImage = R.drawable.angel_cookie_soulstone,
            cookieImage = R.drawable.angel_cookie_character_card,
            cookieImageAnimated = R.drawable.angel_cookie_animated,
            cookieGachaImage = R.drawable.angel_cookie_face_icon,
            type = HEALING,
            rarity = COMMON,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Avocado Cookie",
            soulStoneImage = R.drawable.avocado_cookie_soulstone,
            cookieImage = R.drawable.avocado_cookie_character_card,
            cookieImageAnimated = R.drawable.avocado_cookie_animated,
            cookieGachaImage = R.drawable.avocado_cookie_face_icon,
            type = DEFENSE,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Beet Cookie",
            soulStoneImage = R.drawable.beet_cookie_soulstone,
            cookieImage = R.drawable.beet_cookie_character_card,
            cookieImageAnimated = R.drawable.beet_cookie_animated,
            cookieGachaImage = R.drawable.beet_cookie_face_icon,
            type = RANGED,
            rarity = COMMON,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Ginger Brave",
            soulStoneImage = R.drawable.ginger_brave_soulstone,
            cookieImage = R.drawable.ginger_brave_character_card,
            cookieImageAnimated = R.drawable.ginger_brave_animated,
            cookieGachaImage = R.drawable.ginger_brave_face_icon,
            type = CHARGE,
            rarity = COMMON,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Muscle Cookie",
            soulStoneImage = R.drawable.muscle_cookie_soulstone,
            cookieImage = R.drawable.muscle_cookie_character_card,
            cookieImageAnimated = R.drawable.muscle_cookie_animated,
            cookieGachaImage = R.drawable.muscle_cookie_face_icon,
            type = CHARGE,
            rarity = COMMON,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Ninja Cookie",
            soulStoneImage = R.drawable.ninja_cookie_soulstone,
            cookieImage = R.drawable.ninja_cookie_character_card,
            cookieImageAnimated = R.drawable.ninja_cookie_animated,
            cookieGachaImage = R.drawable.ninja_cookie_face_icon,
            type = AMBUSH,
            rarity = COMMON,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Princess Cookie",
            soulStoneImage = R.drawable.princess_cookie_soulstone,
            cookieImage = R.drawable.princess_cookie_character_card,
            cookieImageAnimated = R.drawable.princess_cookie_animated,
            cookieGachaImage = R.drawable.princess_cookie_face_icon,
            type = CHARGE,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Strawberry Cookie",
            soulStoneImage = R.drawable.strawberry_cookie_soulstone,
            cookieImage = R.drawable.strawberry_cookie_character_card,
            cookieImageAnimated = R.drawable.strawberry_cookie_animated,
            cookieGachaImage = R.drawable.strawberry_cookie_face_icon,
            type = DEFENSE,
            rarity = COMMON,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Wizard Cookie",
            soulStoneImage = R.drawable.wizard_cookie_soulstone,
            cookieImage = R.drawable.wizard_cookie_character_card,
            cookieImageAnimated = R.drawable.wizard_cookie_animated,
            cookieGachaImage = R.drawable.wizard_cookie_face_icon,
            type = MAGIC,
            rarity = COMMON,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Knight Cookie",
            soulStoneImage = R.drawable.soulstone_knight,
            cookieImage = R.drawable.cookie_knight_card,
            cookieImageAnimated = R.drawable.knight_cookie,
            cookieGachaImage = R.drawable.knight_face_icon,
            type = DEFENSE,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = R.drawable.knightskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Blackberry Cookie",
            soulStoneImage = R.drawable.soulstone_blackberry,
            cookieImage = R.drawable.blackberry_cookie,
            cookieImageAnimated = R.drawable.blackberrycookiegachaanimation,
            cookieGachaImage = R.drawable.blackberryhead,
            type = MAGIC,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = 0,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Adventurer Cookie",
            soulStoneImage = R.drawable.soulstone_adventurer,
            cookieImage = R.drawable.adventurercookiegachaanimation,
            cookieImageAnimated = R.drawable.adventurercookiegachaanimation,
            cookieGachaImage = R.drawable.beet_cookie_face_icon,
            type = AMBUSH,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = R.drawable.advskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Pancake Cookie",
            soulStoneImage = R.drawable.soulstone_pancake,
            cookieImage = R.drawable.cookie_pancake_card,
            cookieImageAnimated = R.drawable.pancakecookiegachaanimation,
            cookieGachaImage = R.drawable.pancake_cookie,
            type = AMBUSH,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = R.drawable.pancakeskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Alchemist",
            soulStoneImage = R.drawable.soulstone_alchemist,
            cookieImage = R.drawable.cookie_alchemist_card,
            cookieImageAnimated = R.drawable.alchemist_cookie_alternate,
            cookieGachaImage = R.drawable.alchemisthead,
            type = BOMBER,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = R.drawable.alchskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Cherry Cookie",
            soulStoneImage = R.drawable.soulstone_cherry,
            cookieImage = R.drawable.cookie_cherry_card,
            cookieImageAnimated = R.drawable.cherry_cookie,
            cookieGachaImage = R.drawable.cherryhead,
            type = BOMBER,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = R.drawable.cherryskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Gumball Cookie",
            soulStoneImage = R.drawable.soulstone_gumball,
            cookieImage = R.drawable.cookie_gumball_card,
            cookieImageAnimated = R.drawable.gumball_cookie,
            cookieGachaImage = R.drawable.gumballhead,
            type = BOMBER,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = R.drawable.gumskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Carrot Cookie",
            soulStoneImage = R.drawable.soulstone_carrot,
            cookieImage = R.drawable.cookie_carrot_card,
            cookieImageAnimated = R.drawable.carrot_cookie,
            cookieGachaImage = R.drawable.carrothead,
            type = SUPPORT,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = R.drawable.carrotskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Onion Cookie",
            soulStoneImage = R.drawable.soulstone_onion,
            cookieImage = R.drawable.cookie_onion_card,
            cookieImageAnimated = R.drawable.onion_cookie,
            cookieGachaImage = R.drawable.onion_head,
            type = SUPPORT,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = R.drawable.onionskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Clover Cookie",
            soulStoneImage = R.drawable.soulstone_clover,
            cookieImage = R.drawable.cookie_clover_card,
            cookieImageAnimated = R.drawable.clover_cookie_alternate,
            cookieGachaImage = R.drawable.cloverhead,
            type = SUPPORT,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = R.drawable.cloverskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Custard Cookie III",
            soulStoneImage = R.drawable.soulstone_custard,
            cookieImage = R.drawable.cookie_custard_card,
            cookieImageAnimated = R.drawable.custard_cookie,
            cookieGachaImage = R.drawable.custardhead,
            type = SUPPORT,
            rarity = RARE,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = R.drawable.custardskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Dark Choco Cookie",
            soulStoneImage = R.drawable.soulstone_darkchoco,
            cookieImage = R.drawable.cookie_dark_choco_card,
            cookieImageAnimated = R.drawable.dark_choco_cookie,
            cookieGachaImage = R.drawable.darkchocohead,
            type = CHARGE,
            rarity = EPIC,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = R.drawable.custardskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Purple Yam Cookie",
            soulStoneImage = R.drawable.soulstone_purpleyam,
            cookieImage = R.drawable.cookie_purple_yam_card,
            cookieImageAnimated = R.drawable.purple_yam,
            cookieGachaImage = R.drawable.yamhead,
            type = CHARGE,
            rarity = EPIC,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = R.drawable.yamskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Werewolf Cookie",
            soulStoneImage = R.drawable.soulstone_werewolf,
            cookieImage = R.drawable.cookie_werewolf_card,
            cookieImageAnimated = R.drawable.werewolf_cookie,
            cookieGachaImage = R.drawable.werewolfbase,
            type = CHARGE,
            rarity = EPIC,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = R.drawable.wereskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
        CookieEntity(
            name = "Kumiho Cookie",
            soulStoneImage = R.drawable.soulstone_kumiho,
            cookieImage = R.drawable.cookie_kumiho_card,
            cookieImageAnimated = R.drawable.kumiho_cookie_alternate,
            cookieGachaImage = R.drawable.kumihohead,
            type = CHARGE,
            rarity = LEGENDARY,
            soulStoneCount = 0,
            position = "",
            about = "",
            description = "",
            skill = "",
            skillIcon = R.drawable.kumihoskill,
            quote = "",
            cooldown = 0,
            skillStats = ""
        ),
    )
}